# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-04 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('good_id', models.IntegerField(db_column='GId', primary_key=True, serialize=False)),
                ('book', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=100)),
                ('published', models.CharField(max_length=100)),
                ('sales', models.IntegerField()),
            ],
        ),
    ]
