# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-04 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('good_id', models.IntegerField()),
                ('number', models.IntegerField()),
            ],
        ),
    ]
