# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-05 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.IntegerField(db_column='OId', primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goods', models.ManyToManyField(to='api.GoodsModel')),
            ],
        ),
    ]
